version: '3.8'  # Обновленная версия формата

networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - './.logs/nginx:/var/log/nginx' # Монтирование папки для логов
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - backend
      - frontend
    networks:
      dev:
        aliases:
          - nginx

  backend:
    build:
      context: ./backend
    deploy:
      resources:
        limits:
          cpus: '1.5'  # Максимум 1.5 ядра
          memory: 1G    # Не более 1GB RAM
    networks:
      dev:
        aliases:
          - backend
    volumes:
      - './.logs/backend:/app/logs' # Монтирование папки для логов (если используется логирование)

  frontend:
    build:
      context: ./frontend
    networks:
      dev:
        aliases:
          - frontend
    volumes:
      - './.logs/frontend:/app/logs' # Монтирование папки для логов (если используется логирование)

volumes:
  db_data:  # Определение тома
