server {
    listen 80;
    server_name pubchat.ru www.pubchat.ru;

    # Перенаправление HTTP → HTTPS
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;

    server_name pubchat.ru www.pubchat.ru;

    # Путь к SSL-сертификатам (выпущены Certbot)
    ssl_certificate /etc/letsencrypt/live/pubchat.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/pubchat.ru/privkey.pem;

    # Безопасные настройки SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";

    location / {
        proxy_pass http://frontend:3000/;
    }
    
    location /api/ {
        proxy_pass http://backend:9000/;
    }
}