user root;

events {
}

http {
    # Перенаправление HTTP на HTTPS
    server {
        listen 80;
        server_name pubchat.ru www.pubchat.ru;

        # Перенаправление всех HTTP-запросов на HTTPS
        return 301 https://$host$request_uri;
    }

    # Настройка HTTPS
    server {
        listen 443 ssl;
        server_name pubchat.ru www.pubchat.ru;

        # Пути к SSL-сертификатам (будут автоматически созданы Certbot)
        ssl_certificate /etc/letsencrypt/live/pubchat.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/pubchat.ru/privkey.pem;

        # Настройки безопасности SSL
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;
        ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";

        # Проксирование запросов к frontend и backend
        location / {
            proxy_pass http://frontend:3000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/ {
            proxy_pass http://backend:9000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
