"""message modif

Revision ID: 37af29012686
Revises: 96494eec6eb9
Create Date: 2025-04-09 14:40:03.542212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37af29012686'
down_revision: Union[str, None] = '96494eec6eb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to_uid', sa.UUID(), nullable=True))
    op.drop_constraint('messages_mention_uid_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'messages', ['reply_to_uid'], ['uid'])
    op.drop_column('messages', 'mention_uid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('mention_uid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_mention_uid_fkey', 'messages', 'users', ['mention_uid'], ['uid'])
    op.drop_column('messages', 'reply_to_uid')
    # ### end Alembic commands ###
