"""RoomsMember and RoomBans

Revision ID: 4f3d66790cd3
Revises: 6a3cf6aeaa8f
Create Date: 2025-04-24 16:02:45.780799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f3d66790cd3'
down_revision: Union[str, None] = '6a3cf6aeaa8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room_bans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_uid', sa.UUID(), nullable=True),
    sa.Column('user_uid', sa.UUID(), nullable=True),
    sa.Column('banned_by_uid', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['banned_by_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['room_uid'], ['rooms.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_bans')
    # ### end Alembic commands ###
