"""Tables_new_version

Revision ID: a7e4b3f8d3a1
Revises: ecc7fc6429ec
Create Date: 2025-03-10 16:26:10.337781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e4b3f8d3a1'
down_revision: Union[str, None] = 'ecc7fc6429ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=255), nullable=True),
    sa.Column('global_role', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender'), nullable=True),
    sa.Column('career', sa.String(length=100), nullable=True),
    sa.Column('education', sa.String(length=100), nullable=True),
    sa.Column('marital_status', sa.String(length=50), nullable=True),
    sa.Column('last_online', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_email', 'users', ['email'], unique=False)
    op.create_index('ix_user_gender', 'users', ['gender'], unique=False)
    op.create_index('ix_user_phone', 'users', ['phone'], unique=False)
    op.create_index('ix_user_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uid', sa.UUID(), nullable=True),
    sa.Column('penalty_type', sa.Enum('BAN', 'MUTE', 'WARNING', name='penaltytype'), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('issuer_uid', sa.UUID(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['issuer_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_user_uid', sa.UUID(), nullable=True),
    sa.Column('to_user_uid', sa.UUID(), nullable=True),
    sa.Column('relation_type', sa.Enum('SPOUSE', 'PARENT', 'CHILD', 'SIBLING', 'FRIEND', name='relationshiptype'), nullable=True),
    sa.Column('since', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['to_user_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_user_uid', 'to_user_uid', name='unique_relationship')
    )
    op.create_foreign_key(None, 'messages', 'users', ['author_uid'], ['uid'])
    op.create_foreign_key(None, 'messages', 'users', ['mention_uid'], ['uid'])
    op.create_foreign_key(None, 'private_messages', 'users', ['receiver_uid'], ['uid'])
    op.create_foreign_key(None, 'private_messages', 'users', ['sender_uid'], ['uid'])
    op.create_foreign_key(None, 'room_members', 'users', ['user_uid'], ['uid'])
    op.create_foreign_key(None, 'rooms', 'users', ['owner_uid'], ['uid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rooms', type_='foreignkey')
    op.drop_constraint(None, 'room_members', type_='foreignkey')
    op.drop_constraint(None, 'private_messages', type_='foreignkey')
    op.drop_constraint(None, 'private_messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_table('user_relationships')
    op.drop_table('penalties')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_user_username', table_name='users')
    op.drop_index('ix_user_phone', table_name='users')
    op.drop_index('ix_user_gender', table_name='users')
    op.drop_index('ix_user_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
